### ISSUE TITLE
the training speed problem

### ISSUE THREAD

**Issue by cakaex** [alexfrom0815/Online-3D-BPP-DRL#11]
when the bin size and box size increase, the training is very slow. is there any way to improve it?

**Comment by alexfrom0815** [comment]
> when the bin size

Hi, when the bin size increases, the original heightmap input (state) to the CNN also gets larger, which slows down the algorithm. 

The good news is that our new work no longer uses the heightmap representation, the input container size and item size can be arbitrary and this does not affect the speed of training. If you are interested, you can find our new job at https://github.com/alexfrom0815/Online-3D-BPP-PCT.
