### ISSUE TITLE
visual graph

### ISSUE THREAD

**Issue by github097** [alexfrom0815/Online-3D-BPP-DRL#13]
Hello, I want to reproduce the three-dimensional packing diagram in this paper, such as Figure 1, Figure 4, Figure 18, Figure 19. How to generate graphics like this？What should I do, please ? 
Looking forward to your reply, thank you for sharing
![image](https://user-images.githubusercontent.com/101797011/171600409-4fbb1093-4c3a-4399-9a6b-d5d8850e38b5.png)

**Comment by alexfrom0815** [comment]
Hello! The figure work I made in the paper was rendered using 'deep exploration'. You can use this tool to manually design what you needed. Best wishes!

**Comment by sejmoonwei** [comment]
> Hello! The figure work I made in the paper was rendered using 'deep exploration'. You can use this tool to manually design what you needed. Best wishes!

Thank you for sharing this great work. I have a question though, that is ,what simulation tools did you use in this work? I mean, the tool for visualization during training&testing phase. Is that mojoco or gazebo?As in the following picture.
Thanks in advance.
![0107_1](https://user-images.githubusercontent.com/60536424/211145459-d58a2316-67ad-4edb-b900-18e1feed6418.jpg)
