### ISSUE TITLE
Learning Online-3D-BPP-DRL - Get amount of the used containers

### ISSUE THREAD

**Issue by alex-ams** [alexfrom0815/Online-3D-BPP-DRL#15]
Hello,

I'm studying the 3D Bin packing with this repository: [https://github.com/alexfrom0815/Online-3D-BPP-DRL].
I have some troubles with the evaluation.py file. I'm using my own data by generating a ".pt" but I don't know how to retrieve the number of used containers and the number of items packed in each one.
Could you please help with this?

Thanks in advance

**Comment by alex-ams** [comment]
Hello, 

In evaluation.py, we get eval_ens.space.boxes and we display the list after running the evaluation function. But I notice that one item in this list is not present in the item list given to evaluate the model. 
Can you help me with this also? 

Thanks in advance

**Comment by alexfrom0815** [comment]
> Hello,
> 
> I'm studying the 3D Bin packing with this repository: [https://github.com/alexfrom0815/Online-3D-BPP-DRL]. I have some troubles with the evaluation.py file. I'm using my own data by generating a ".pt" but I don't know how to retrieve the number of used containers and the number of items packed in each one. Could you please help with this?
> 
> Thanks in advance

Hello! In our problem, we assume that only one container is used for loading online items. When the container is full, it will be reset and another packing episode starts. You can print 'self.boxes' in 'envs/bpp0/space.py' for reading information of the packed items.

**Comment by alexfrom0815** [comment]
> 



> Hello,
> 
> In evaluation.py, we get eval_ens.space.boxes and we display the list after running the evaluation function. But I notice that one item in this list is not present in the item list given to evaluate the model. Can you help me with this also?
> 
> Thanks in advance

‘eval_ens.space.boxes’ records all the boxes that were **successfully** loaded into the container. For the online packing problem, when a box that cannot be placed is encountered, the round ends. That is, the last box of each packing round will not be recorded in 'eval_ens.space.boxes'.
