### ISSUE TITLE
How to map to real-world data?

### ISSUE THREAD

**Issue by gokul-gokz** [alexfrom0815/Online-3D-BPP-DRL#18]
Hello 
  Thanks for sharing this awesome work. 

  The proposed method works good in the simulation for a smaller statespace. But how did you map the algorithm to the real world input such as high resolution image(ex:640x480) from camera.

**Comment by alexfrom0815** [comment]
I recommend our new work https://github.com/alexfrom0815/Online-3D-BPP-PCT, which can work without resolution limitations. Best wishes!
