### ISSUE TITLE
a mistake that can not solve

### ISSUE THREAD

**Issue by llzll1031** [alexfrom0815/Online-3D-BPP-DRL#24]
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params, jobz, uplo, n, CUDA_R_32F, reinterpret_cast&lt;void*&gt;(A), lda, CUDA_R_32F, reinterpret_cast&lt;void*&gt;(W), CUDA_R_32F, reinterpret_cast&lt;void*&gt;(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast&lt;void*&gt;(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN.  
can we run it on ubuntu 1804？

**Comment by llzll1031** [comment]
Maybe I need to know your version of CUDA

**Comment by JieHaoL** [comment]
> torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params, jobz, uplo, n, CUDA_R_32F, reinterpret_cast&lt;void*&gt;(A), lda, CUDA_R_32F, reinterpret_cast&lt;void*&gt;(W), CUDA_R_32F, reinterpret_cast&lt;void*&gt;(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast&lt;void*&gt;(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN. can we run it on ubuntu 1804？

hello, I also encountered this problem, have you fixed it yet?
