### ISSUE TITLE
gym registration

### ISSUE THREAD

**Issue by strongteck** [alexfrom0815/Online-3D-BPP-DRL#3]
Hello,

I tried to register the "envs/Bpp-v0" evirionment by adding the following code in file ./Online-3D-BPP-DRL/envs/bpp0/__init__.py, but I am getting errors as "gym.error.UnregisteredEnv: No registered env with id: Bpp-v0".

Could you please advise?

Thank you.

----
from gym.envs.registration import register
register(
    id='Bpp-v0',
    entry_point='bpp0.bin3D:PackingGame',
)
---

**Comment by alexfrom0815** [comment]
Hello, I’m not sure what you have encountered here, but I think you can try the following steps:

1. Install gym and find the package path of your gym, you type print(gym.__path__) in your python interpreter to find it.
2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
3. Add registration to 'your gym path/envs/__init__.py', The newly added content should be:
register(
    id='Bpp-v0',
    entry_point='gym.envs.user.bpp0:PackingGame',
)

This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!

Best wishes!

**Comment by alexfrom0815** [comment]
'gym.__path__' and '__init__.py'

**Comment by alexfrom0815** [comment]
"__path__"

**Comment by strongteck** [comment]
That perfectly solves the problem!
Many thanks for help.

**Comment by qingweihk** [comment]
> Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> 
> 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
>    register(
>    id='Bpp-v0',
>    entry_point='gym.envs.user.bpp0:PackingGame',
>    )
> 
> This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> 
> Best wishes!

Hello, I have followed your steps but got the following error:

AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'

Any helps? Many thanks.

**Comment by F2Wang** [comment]
> > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > 
> > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> >    register(
> >    id='Bpp-v0',
> >    entry_point='gym.envs.user.bpp0:PackingGame',
> >    )
> > 
> > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > Best wishes!
> 
> Hello, I have followed your steps but got the following error:
> 
> AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> 
> Any helps? Many thanks.

I have the same problem, have you found a solution yet?

**Comment by qingweihk** [comment]
> > > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > > 
> > > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> > >    register(
> > >    id='Bpp-v0',
> > >    entry_point='gym.envs.user.bpp0:PackingGame',
> > >    )
> > > 
> > > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > > Best wishes!
> > 
> > 
> > Hello, I have followed your steps but got the following error:
> > AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> > Any helps? Many thanks.
> 
> I have the same problem, have you found a solution yet?

Not yet.

**Comment by alexfrom0815** [comment]
Sorry, I am unable to determine the cause of this error (gym installation or 'Bpp-v0' registration) due to insufficient information, but I can provide a debugging suggestion. 
You can change the variable value of  'env_name' in config.py from 'Bpp-v0' to gym's original environment, such as 'CartPole-v0', (this environment is also registered in 'your gym path/envs/`__init__`. py'). If the environment of 'CartPole-v0' cannot be loaded, then there is a problem with the installation of gym. Otherwise, the problem lies in the registration of the environment of 'Bpp-v0'. In this case, you can also compare the registration format of the environment 'CartPole-v0' under 'your gym path/envs/`__init__`. py' to check whether the environment 'Bpp-v0' is registered correctly. Good luck!

**Comment by alexfrom0815** [comment]
> > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > 
> > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> >    register(
> >    id='Bpp-v0',
> >    entry_point='gym.envs.user.bpp0:PackingGame',
> >    )
> > 
> > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > Best wishes!
> 
> Hello, I have followed your steps but got the following error:
> 
> AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> 
> Any helps? Many thanks.

Sorry, I am unable to determine the cause of this error (gym installation or 'Bpp-v0' registration) due to insufficient information, but I can provide a debugging suggestion. 

You can change the variable value of  'env_name' in config.py from 'Bpp-v0' to gym's original environment, such as 'CartPole-v0', (this environment is also registered in 'your gym path/envs/`__init__`. py'). If the environment of 'CartPole-v0' cannot be loaded, then there is a problem with the installation of gym. Otherwise, the problem lies in the registration of the environment of 'Bpp-v0'. In this case, you can also compare the registration format of the environment 'CartPole-v0' under 'your gym path/envs/`__init__`. py' to check whether your 'Bpp-v0' is registered correctly. Good luck!

**Comment by qingweihk** [comment]
> > > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > > 
> > > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> > >    register(
> > >    id='Bpp-v0',
> > >    entry_point='gym.envs.user.bpp0:PackingGame',
> > >    )
> > > 
> > > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > > Best wishes!
> > 
> > 
> > Hello, I have followed your steps but got the following error:
> > AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> > Any helps? Many thanks.
> 
> Sorry, I am unable to determine the cause of this error (gym installation or 'Bpp-v0' registration) due to insufficient information, but I can provide a debugging suggestion.
> 
> You can change the variable value of 'env_name' in config.py from 'Bpp-v0' to gym's original environment, such as 'CartPole-v0', (this environment is also registered in 'your gym path/envs/`__init__`. py'). If the environment of 'CartPole-v0' cannot be loaded, then there is a problem with the installation of gym. Otherwise, the problem lies in the registration of the environment of 'Bpp-v0'. In this case, you can also compare the registration format of the environment 'CartPole-v0' under 'your gym path/envs/`__init__`. py' to check whether your 'Bpp-v0' is registered correctly. Good luck!

Many thanks

**Comment by F2Wang** [comment]
> > > > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > > > 
> > > > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > > > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > > > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> > > >    register(
> > > >    id='Bpp-v0',
> > > >    entry_point='gym.envs.user.bpp0:PackingGame',
> > > >    )
> > > > 
> > > > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > > > Best wishes!
> > > 
> > > 
> > > Hello, I have followed your steps but got the following error:
> > > AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> > > Any helps? Many thanks.
> > 
> > 
> > Sorry, I am unable to determine the cause of this error (gym installation or 'Bpp-v0' registration) due to insufficient information, but I can provide a debugging suggestion.
> > You can change the variable value of 'env_name' in config.py from 'Bpp-v0' to gym's original environment, such as 'CartPole-v0', (this environment is also registered in 'your gym path/envs/`__init__`. py'). If the environment of 'CartPole-v0' cannot be loaded, then there is a problem with the installation of gym. Otherwise, the problem lies in the registration of the environment of 'Bpp-v0'. In this case, you can also compare the registration format of the environment 'CartPole-v0' under 'your gym path/envs/`__init__`. py' to check whether your 'Bpp-v0' is registered correctly. Good luck!
> 
> Many thanks

Hi, don't know if you figured out the issue, for me I should have copied bpp0 folder to under Online-3D-BPP-DRL/envs to gym path/envs/user/bpp0, while I only created a new folder under that path and put an init file in there...

**Comment by strongteck** [comment]
> > > > > Hello, I’m not sure what you have encountered here, but I think you can try the following steps:
> > > > > 
> > > > > 1. Install gym and find the package path of your gym, you type print(gym.`__path__`) in your python interpreter to find it.
> > > > > 2. Create a folder named ‘user’ under 'your gym path/envs/' and move the 'bpp0' folder into 'your gym path/envs/user', the final path should be 'your gym path/envs/user/bpp0'
> > > > > 3. Add registration to 'your gym path/envs/`__init__.py`', The newly added content should be:
> > > > >    register(
> > > > >    id='Bpp-v0',
> > > > >    entry_point='gym.envs.user.bpp0:PackingGame',
> > > > >    )
> > > > > 
> > > > > This is my solution, maybe not so elegant, but in my experience it works well, I hope it can solve your problem!
> > > > > Best wishes!
> > > > 
> > > > 
> > > > Hello, I have followed your steps but got the following error:
> > > > AttributeError: module 'gym.envs.user.bpp0' has no attribute 'PackingGame'
> > > > Any helps? Many thanks.
> > > 
> > > 
> > > Sorry, I am unable to determine the cause of this error (gym installation or 'Bpp-v0' registration) due to insufficient information, but I can provide a debugging suggestion.
> > > You can change the variable value of 'env_name' in config.py from 'Bpp-v0' to gym's original environment, such as 'CartPole-v0', (this environment is also registered in 'your gym path/envs/`__init__`. py'). If the environment of 'CartPole-v0' cannot be loaded, then there is a problem with the installation of gym. Otherwise, the problem lies in the registration of the environment of 'Bpp-v0'. In this case, you can also compare the registration format of the environment 'CartPole-v0' under 'your gym path/envs/`__init__`. py' to check whether your 'Bpp-v0' is registered correctly. Good luck!
> > 
> > 
> > Many thanks
> 
> Hi, don't know if you figured out the issue, for me I should have copied bpp0 folder to under Online-3D-BPP-DRL/envs to gym path/envs/user/bpp0, while I only created a new folder under that path and put an init file in there...

Make sure gym is well installed before you dig deeper to the copy folder stuff by testing it with a standard environment (say 
'CartPole-v0' as pointed by alex).
