### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by Chengjlzzz** [alexfrom0815/Online-3D-BPP-DRL#7]
When I tried to use a different dataset to train new model , there is a error:
RuntimeError: CUDA out of memory. Tried to allocate 828.00 MiB (GPU 0; 8.00 GiB total capacity; 5.02 GiB already allocated; 209.38 MiB free; 5.18 GiB reserved in total by PyTorch)

**Comment by alexfrom0815** [comment]
The existing CNN model is designed for the packing problem with a resolution of 10*10. If you want to test the packing problem with a larger resolution, the CNN model in the CNNPro class （'./acktr/model.py') needs to be modified accordingly to reduce GPU resource usage.
