### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Policy: 	size mismatch for base.critic_linear.bias

### ISSUE THREAD

**Issue by cakaex** [alexfrom0815/Online-3D-BPP-DRL#8]
When I tried to test the trained model (using a linear schedule on the learning rate in config.py),there is an error:
RuntimeError: Error(s) in loading state_dict for Policy:
	size mismatch for base.critic_linear.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).

**Comment by alexfrom0815** [comment]
This may be caused by different python versions or different torch versions. The loading function is available in python 3.7 & torch 1.1~1.5

**Comment by cakaex** [comment]
Thanks a lot!

**Comment by MLrookiexxy** [comment]
> When I tried to test the trained model (using a linear schedule on the learning rate in config.py),there is an error: RuntimeError: Error(s) in loading state_dict for Policy: size mismatch for base.critic_linear.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).

I also encountered the same problem. I downloaded Torch versions 1.1-1.5, but still reported this error. How did you solve it?
